[package]
name = "rust_shape"
version = "0.1.0"
authors = ["Zois Pagoulatos <zpagoulatos@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
